typedef enum{Sno,Shh,Ssp,Sbi,Spk,Sbo,LSPR}sprid;
void notex();
void retex();
void drawSpr(sprid s,int x,int y);
void glPt(int,int);
void glCircLines(int x,int y,float r);
void glLine(float x1,float y1,float x2,float y2);
void glTriangleLines(float,float,float,float,float,float);
void glTri(int,int,int);
void sprInit();
void sprBegin();
void sprFg();
void sprEnd();
int sprInput();
void glBlack(float);
void glWhite(float);
void enableBlend();
void disableBlend();
void glRect(float,float,float,float);
uint32_t rnd();